package com.bookstore.model;
// Generated Apr 18, 2020, 10:53:40 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {

	private Integer orderFk;
	private Integer bookFk;
	private int quantity;
	private float subTotal;

	public OrderDetailId() {
	}

	public OrderDetailId(int quantity, float subTotal) {
		this.quantity = quantity;
		this.subTotal = subTotal;
	}

	public OrderDetailId(Integer orderFk, Integer bookFk, int quantity, float subTotal) {
		this.orderFk = orderFk;
		this.bookFk = bookFk;
		this.quantity = quantity;
		this.subTotal = subTotal;
	}

	@Column(name = "order_fk")
	public Integer getOrderFk() {
		return this.orderFk;
	}

	public void setOrderFk(Integer orderFk) {
		this.orderFk = orderFk;
	}

	@Column(name = "book_fk")
	public Integer getBookFk() {
		return this.bookFk;
	}

	public void setBookFk(Integer bookFk) {
		this.bookFk = bookFk;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "sub_total", nullable = false, precision = 12, scale = 0)
	public float getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(float subTotal) {
		this.subTotal = subTotal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return ((this.getOrderFk() == castOther.getOrderFk()) || (this.getOrderFk() != null
				&& castOther.getOrderFk() != null && this.getOrderFk().equals(castOther.getOrderFk())))
				&& ((this.getBookFk() == castOther.getBookFk()) || (this.getBookFk() != null
						&& castOther.getBookFk() != null && this.getBookFk().equals(castOther.getBookFk())))
				&& (this.getQuantity() == castOther.getQuantity()) && (this.getSubTotal() == castOther.getSubTotal());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderFk() == null ? 0 : this.getOrderFk().hashCode());
		result = 37 * result + (getBookFk() == null ? 0 : this.getBookFk().hashCode());
		result = 37 * result + this.getQuantity();
		result = 37 * result + (int) this.getSubTotal();
		return result;
	}

}
